stages:
  - tweet

tweet:
  stage: tweet
  image:
    name: alekzonder/puppeteer:latest
  variables:
    TWITTER_APP_KEY: $TWITTER_APP_KEY
    TWITTER_APP_SECRET: $TWITTER_APP_SECRET
    TWITTER_ACCESS_TOKEN: $TWITTER_ACCESS_TOKEN
    TWITTER_ACCESS_SECRET: $TWITTER_ACCESS_SECRET
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - cd twitter-bot
    - yarn install --frozen-lockfile
    - yarn run solve
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - twitter-bot/node_modules/
