stages:
  - tweet

tweet:
  stage: tweet
  image:
    name: nathanfriend/docker-puppeteer:node-16
  variables:
    TWITTER_APP_KEY: $TWITTER_APP_KEY
    TWITTER_APP_SECRET: $TWITTER_APP_SECRET
    TWITTER_ACCESS_TOKEN: $TWITTER_ACCESS_TOKEN
    TWITTER_ACCESS_SECRET: $TWITTER_ACCESS_SECRET
    IMGUR_CLIENT_ID: $IMGUR_CLIENT_ID
    IMGUR_CLIENT_SECRET: $IMGUR_CLIENT_SECRET
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == "web")
  script:
    - cd twitter-bot
    - yarn install --frozen-lockfile
    - yarn run solve
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - twitter-bot/node_modules/
